language: node_js
node_js:
 - 6.9.1

before_install:
 - npm install -g npm@6.4.1
 - npm --version

env:
 global:
  - secure: "mOf/8UBsqp7o9PYSCdgrZXoRUa1zSiaf8YmzqpS0huamN6FZKXTD6XXbeswgL+As7WGB/LsEPkQyVoejY41SVMJkB6UXRFa/y3Ecd2kmNgahXI6VkkKXNzoEs5JBwcr9QiCPzoUREr9KKqcNokjY7l6+qx1fBAU80W8Nq2eQ7nc="

after_success:
 - chmod -R 777 ./ci-release.sh
 - ./ci-release.sh
